spring:
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/shopflow}
        username: ${DB_USERNAME:shopflow}
        password: ${DB_PASSWORD:shopflow}
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6380}

server:
    port: 8080
